### ISSUE TITLE
Yarn create not working 😒

### ISSUE THREAD

**Issue by cobraz** [bjerkio/create-bjerk-typescript#64]
Seems like the command line utility is trying to copy a file that does not exist. Not sure if this is caused by files not being included in the NPM package or what.

## Steps to reproduce

1. `yarn create bjerk-typescript hello-world`

This will output the following:

```shell
➜  /tmp yarn create bjerk-typescript hello-world
yarn create v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Installed "create-bjerk-typescript@2.1.2" with binaries:
      - create-bjerk-typescript
[#####################################################################] 153/153Bootstrapping

Summary:
Destination: /private/tmp/hello-world
App: hello-world

Copying Project Files ...
Copying Templates ...
node:internal/fs/utils:345
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat '/Users/cobraz/.config/yarn/global/node_modules/create-bjerk-typescript/templates/.github/workflows/workflow.yml'
    at Object.lstatSync (node:fs:1529:3)
    at Object.lstatSync (/Users/cobraz/.config/yarn/global/node_modules/graceful-fs/polyfills.js:311:34)
    at statFunc (/Users/cobraz/.config/yarn/global/node_modules/create-bjerk-typescript/node_modules/fs-extra/lib/util/stat.js:24:20)
    at getStatsSync (/Users/cobraz/.config/yarn/global/node_modules/create-bjerk-typescript/node_modules/fs-extra/lib/util/stat.js:25:19)
    at Object.checkPathsSync (/Users/cobraz/.config/yarn/global/node_modules/create-bjerk-typescript/node_modules/fs-extra/lib/util/stat.js:67:33)
    at Object.copySync (/Users/cobraz/.config/yarn/global/node_modules/create-bjerk-typescript/node_modules/fs-extra/lib/copy/copy-sync.js:24:38)
    at /Users/cobraz/.config/yarn/global/node_modules/create-bjerk-typescript/cmd/create-bjerk-typescript/index.cjs:100:11
    at Array.forEach (<anonymous>)
    at main (/Users/cobraz/.config/yarn/global/node_modules/create-bjerk-typescript/cmd/create-bjerk-typescript/index.cjs:99:13)
    at Object.<anonymous> (/Users/cobraz/.config/yarn/global/node_modules/create-bjerk-typescript/cmd/create-bjerk-typescript/index.cjs:139:1) {
  errno: -2,
  syscall: 'lstat',
  code: 'ENOENT',
  path: '/Users/cobraz/.config/yarn/global/node_modules/create-bjerk-typescript/templates/.github/workflows/workflow.yml'
}
error Command failed.
Exit code: 1
Command: /Users/cobraz/.yarn/bin/create-bjerk-typescript
Arguments: hello-world
Directory: /private/tmp
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

**Comment by cobraz** [comment]
It looks like it's looking for files located in ` /Users/cobraz/.config/yarn/global/node_modules/create-bjerk-typescript/templates/.github/workflows/`

```shell
➜  /tmp ls -l /Users/cobraz/.config/yarn/global/node_modules/create-bjerk-typescript/templates/
total 8
-rw-r--r--  1 cobraz  staff  325 Sep 12 15:41 README.md
➜  /tmp ls -l /Users/cobraz/.config/yarn/global/node_modules/create-bjerk-typescript/templates/.
./               ../              .gitignore.root
```

I can confirm this directory does not contain this file.

AFAIK, this is new behaviour after updating to the latest yarn.
